#!/bin/bash

MIRIFLAGS="-Zmiri-disable-isolation ${MIRIFLAGS:-}"\
    cargo +nightly miri test --features async &&
MIRIFLAGS="-Zmiri-disable-isolation ${MIRIFLAGS:-}"\
    cargo +nightly miri test --test stack --no-default-features